---
title: "SIMD 2020 alternate plots"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
    code_folding: hide
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intro

Look at some variables that usually get ignored

###Packages

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggthemes)
library(readxl)
library(janitor)
library(hrbrthemes)
library(scales)
library(ggdark)
library(ggbeeswarm)
library(gganimate)

theme_set(theme_minimal(base_size = 26, base_family = "Roboto"))
```


### Data

From the SG SIMD2020 webpage

```{r}
simd <- read_excel("raw_data/SIMD_2020_Datazone_lookup_tool.xlsx", sheet = 3)
```

```{r}
simd %>% 
  select(DZ, DZname,IZname, LAname,SIMD2020_Access_Domain_Rank,
         SIMD2020_Crime_Domain_Rank,SIMD2020_Decile,
         SIMD2020_Income_Domain_Rank, SIMD2020_Employment_Domain_Rank,
         SIMD2020_Education_Domain_Rank, SIMD2020_Health_Domain_Rank,
         SIMD2020_Housing_Domain_Rank, SIMD2020_Income_Domain_Rank) %>% 
  rename(Access = SIMD2020_Access_Domain_Rank,
         Crime = SIMD2020_Crime_Domain_Rank,
         Decile = SIMD2020_Decile,
         Income = SIMD2020_Income_Domain_Rank, 
         Employment = SIMD2020_Employment_Domain_Rank,
         Education = SIMD2020_Education_Domain_Rank,
         Health = SIMD2020_Health_Domain_Rank,
         Housing = SIMD2020_Housing_Domain_Rank, 
         Income = SIMD2020_Income_Domain_Rank) %>% 
  tidyr::gather(key = "metric", value = "rank",-c(DZ, DZname, IZname, LAname, Decile)) -> ranked

ranked <- ranked %>% 
  mutate(rescaled_rank = rescale(rank))
```


## Rank

```{r, fig.width=20, fig.height=18}
ranked %>% 
   ggplot(aes(metric,y = rank)) +
  geom_point(aes(colour = rank), position = position_jitter(width = 0.2),alpha = 0.2) +
 scale_colour_viridis_c(option = "plasma") +
  facet_wrap(~ LAname, ncol = 4) + 
  theme_ft_rc(base_size = 12) +
  ggExtra::rotateTextX() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank()) +
  labs(title = "SIMD 2020 Domains by Data Zone",
        subtitle = "Grouped by Local Authority",
       x = "Domain",
       y = "",
       fill = "SIMD decile", 
     caption = "@_johnmackintosh \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/") 

```



```{r}
ggsave("plots/simd_domain_rank_plot.png", width = 20, height = 18)
```




##  Rescaled Rank

```{r, fig.width=20, fig.height=18}
ranked %>% 
   ggplot(aes(metric,y = rescaled_rank)) +
  geom_point(aes(colour = rescaled_rank), position = position_jitter(),alpha = 0.4) +
 scale_colour_viridis_c(option = "plasma") +
  facet_wrap(~ LAname, ncol = 4) + 
  theme_ft_rc(base_size = 12) +
  ggExtra::rotateTextX() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank()) +
  labs(title = "Rescaled SIMD 2020 Domains by Data Zone",
        subtitle = "Grouped by Local Authority",
       x = "Domain name",
       y = "",
       fill = "SIMD decile", 
     caption = "@_johnmackintosh \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/") 

```



```{r}
ggsave("plots/simd_domain_rescaled_rank_plot.png", width = 20, height = 18)
```



## dark theme orange to blue

```{r}
ranked %>% 
   ggplot(aes(metric,y = rank)) +
 geom_point(aes(colour = rank), position = position_jitter(width = 0.2),alpha = 0.3) +
  facet_wrap(~ LAname, ncol = 4) + 
 dark_theme_minimal() + 
  scale_color_gradient(low = "orange", high = "blue") +
  ggExtra::rotateTextX() +
  theme(legend.position = "bottom",
       axis.text.y = element_blank()) +
  labs(title = "SIMD 2020 domains by Data Zone",
        subtitle = "Grouped by Local Authority",
       x = "Domain",
       y = "",
       fill = "SIMD decile", 
       caption = "@_johnmackintosh \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/") 

```


```{r}
ggsave("plots/simd_domain_rank_plot_org_blu.png", width = 20, height = 18)
```


## Parochial 

```{r}
ranked %>% 
  filter(LAname == 'Highland') %>% 
  ggplot(aes(metric,y = rank, colour = rank)) +
 # geom_point(aes(colour = rank), position = position_jitter(),alpha = 0.6) +
  geom_beeswarm(alpha = 0.6) +
 scale_colour_viridis_c(option = "plasma") +
  facet_wrap(~ IZname, labeller = labeller(groupwrap = label_wrap_gen(25, 
                                                          multi_line = TRUE))) + 
  #theme_ft_rc(base_size = 12) +
  dark_theme_minimal(base_size = 12) +
  ggExtra::rotateTextX() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank()) +
  labs(title = " Highland SIMD domains by Intermediate Zone",
        subtitle = "",
       x = "Domain",
       y = "",
       #fill = "SIMD decile", 
     caption = "@_johnmackintosh \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/") 
  
```

```{r}
ggsave("plots/simd_domain_Highland_IZ.png", width = 20, height = 18)
```



## General Beeswarm

```{r}
ranked %>% 
  filter(LAname == 'Highland') %>% 
  ggplot(aes(metric,y = rank, colour = rank)) +
  geom_beeswarm(alpha = 0.6) +
 scale_colour_viridis_c(option = "plasma") +
 theme_ft_rc(base_size = 12) +
  #dark_theme_minimal(base_size = 12) +
  #ggExtra::rotateTextX() +
 # theme(legend.position = "bottom") +
  theme(legend.position = "none") +
        #axis.text.y = element_blank()) +
  labs(title = "Highland SIMD 2020 by domain",
        subtitle = "",
       x = "",
       y = "",
       fill = "SIMD decile", 
     caption = "@_johnmackintosh / @_davidhen \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/")  +
  coord_flip()
```



```{r}
ggsave("plots/simd_domain_Highland_beeswarm.png", width = 8, height = 6)

```


## Local Authority Beeswarm
```{r}
ranked %>% 
  ggplot(aes(metric,y = rank, colour = rank)) +
  geom_beeswarm(alpha = 0.5) + 
  scale_colour_viridis_c(option = "plasma") +
  theme_ft_rc(base_size = 12) +
  facet_wrap(~ LAname, ncol = 4) + 
  ggExtra::rotateTextX() +
  theme(legend.position = "bottom",
       axis.text.y = element_blank()) +
  labs(title = "SIMD 2020 domains by Data Zone",
        subtitle = "Grouped by Local Authority",
       x = "",
       y = "",
       fill = "SIMD decile", 
       caption = "@_johnmackintosh \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/") 
```

```{r}
ggsave("plots/simd_domain_LA_beeswarm.png", width = 20, height = 18)
```



```{r}
ranked %>% 
  filter(LAname %in% c('City of Edinburgh', 'Glasgow City')) %>% 
  ggplot(aes(LAname,y = rank, colour = rank)) +
  geom_beeswarm(alpha = 0.5) + 
  scale_colour_viridis_c(option = "plasma") +
  #scale_color_gradient(low = "orange", high = "blue") +
  theme_ft_rc(base_size = 12) +
  facet_wrap(~ metric, nrow = 1) + 
  ggExtra::rotateTextX() +
  theme(legend.position = "bottom",
       axis.text.y = element_blank()) +
  labs(title = "Scotland's Big 2 - SIMD 2020 by Domain",
        subtitle = "",
       x = "",
       y = "",
       fill = "SIMD decile", 
       caption = "@_johnmackintosh \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/") 
```


```{r}
ggsave("plots/simd_domain_big2_beeswarm.png", width = 14, height = 8)
```


## Rotated

```{r}
ranked %>% 
  filter(LAname %in% c('City of Edinburgh', 'Glasgow City')) %>% 
  ggplot(aes(LAname,y = rank, colour = rank)) +
  geom_beeswarm(alpha = 0.5) + 
  scale_colour_viridis_c(option = "plasma") +
  #scale_color_gradient(low = "orange", high = "blue") +
  theme_ft_rc(base_size = 12) +
  facet_wrap(~ metric, nrow = 1) + 
  ggExtra::rotateTextX() +
  ggExtra::removeGrid() +
  theme(legend.position = "bottom" ,
       axis.text.x = element_blank()) +
  labs(title = "Scotland's Big 2 - SIMD 2020 by Domain",
        subtitle = "",
       x = "",
       y = "",
       fill = "SIMD decile", 
       caption = "@_johnmackintosh / @_davidhen \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/") +
  coord_flip()
```



```{r}
ggsave("plots/simd_domain_big2_rotated_beeswarm.png", width = 14, height = 10)
```


## Plot

```{r, fig.width=20, fig.height=18}
base_plot <- 
  ranked %>% 
  filter(LAname %in% c('City of Edinburgh', 'Glasgow City')) %>% 
  ggplot(aes(LAname,y = rank, colour = rank)) +
  geom_beeswarm(alpha = 0.5) + 
  scale_colour_viridis_c(option = "plasma") +
  #scale_color_gradient(low = "orange", high = "blue") +
  theme_ft_rc(base_size = 12) +
  facet_wrap(~ metric, nrow = 1) + 
  ggExtra::rotateTextX() +
  ggExtra::removeGrid() +
  theme(legend.position = "bottom" ,
       axis.text.x = element_blank()) +
  labs(title = "Scotland's Big 2 - SIMD 2020 by Domain",
        subtitle = "",
       x = "",
       y = "",
       fill = "SIMD decile", 
       caption = "@_johnmackintosh / @_davidhen \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/") +
  coord_flip()  

anime <- 
  base_plot +
  transition_states(metric,
                    transition_length = 6,
                    state_length = 3) +
  shadow_mark(past = TRUE, future = FALSE) +
  ease_aes("cubic-in-out") #+
  # labs(subtitle = "Year: {closest_state}", 
  #      title = "Change in percentage living in SIMD deciles by Local Authority",
  #      x = "",
  #      y = "",
  #      fill = "SIMD Decile",
  #      caption = "Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/")
    


animate(anime, width = 1400, height = 1000)
```



```{r}
anim_save(filename = "plots/two_cities.gif", animation = last_animation())
```




## working Age

```{r}
simd %>% 
  ggplot(aes(SIMD2020_Quintile,y = Working_Age_Population, 
             colour = SIMD2020_Employment_Domain_Rank)) +
  geom_beeswarm(alpha = 0.5) + 
  scale_colour_viridis_c(option = "plasma") +
  theme_ft_rc(base_size = 12) +
  facet_wrap(~ LAname, ncol = 4) + 
 scale_x_discrete(breaks = c(1,2,3,4,5), labels = c(1,2,3, 4,5), 
                  limits = c("1", "2", "3", "4","5")) +
  ggExtra::rotateTextX() +
  ggExtra::removeGrid() +
  theme(legend.position = "bottom",
       axis.text.y = element_blank()) +
  labs(title = "Working Age Population by SIMD 2020 Quintile",
        subtitle = "Grouped by Local Authority, scaled by Employment Domain Rank",
       x = "Quintile",
       y = "Working Age Population",
       caption = "@_johnmackintosh \n Data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/") 
```


```{r}
ggsave("plots/simd_working_age_population.png", width = 20, height = 18)
```



## Session Info

```{r}
sessionInfo()
```

